// Do NOT edit this file directly. Make your changes to esp-metadata,
// then run `cargo xtask update-metadata`.

/// The name of the chip as `&str`
///
/// # Example
///
/// ```rust, no_run
/// use esp_hal::chip;
/// let chip_name = chip!();
#[doc = concat!("assert_eq!(chip_name, ", chip!(), ")")]
/// ```
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! chip {
    () => {
        "esp32s31"
    };
}
/// The pretty name of the chip as `&str`
///
/// # Example
///
/// ```rust, no_run
/// use esp_hal::chip;
/// let chip_name = chip_pretty!();
#[doc = concat!("assert_eq!(chip_name, ", chip_pretty!(), ")")]
/// ```
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! chip_pretty {
    () => {
        "ESP32-S31"
    };
}
/// The properties of this chip and its drivers.
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! property {
    ("chip") => {
        "esp32s31"
    };
    ("arch") => {
        "riscv"
    };
    ("cores") => {
        2
    };
    ("cores", str) => {
        stringify!(2)
    };
    ("trm") => {
        "https://github.com/espressif/esp-idf/tree/e88643bc619dff3c21b51705113bb488c9bc0990/components/soc/esp32s31"
    };
    ("aes.has_split_text_registers") => {
        true
    };
    ("aes.endianness_configurable") => {
        false
    };
    ("dma.mem2mem_requires_peripheral") => {
        false
    };
    ("dma.ext_mem_configurable_block_size") => {
        false
    };
    ("dma.separate_in_out_interrupts") => {
        true
    };
    ("dma.gdma_version") => {
        2
    };
    ("dma.gdma_version", str) => {
        stringify!(2)
    };
    ("gpio.version") => {
        3
    };
    ("gpio.version", str) => {
        stringify!(3)
    };
    ("gpio.has_bank_1") => {
        true
    };
    ("gpio.has_input_sync") => {
        true
    };
    ("gpio.gpio_function") => {
        1
    };
    ("gpio.gpio_function", str) => {
        stringify!(1)
    };
    ("gpio.constant_0_input") => {
        192
    };
    ("gpio.constant_0_input", str) => {
        stringify!(192)
    };
    ("gpio.constant_1_input") => {
        128
    };
    ("gpio.constant_1_input", str) => {
        stringify!(128)
    };
    ("gpio.remap_iomux_pin_registers") => {
        false
    };
    ("gpio.func_in_sel_offset") => {
        0
    };
    ("gpio.func_in_sel_offset", str) => {
        stringify!(0)
    };
    ("gpio.input_signal_max") => {
        107
    };
    ("gpio.input_signal_max", str) => {
        stringify!(107)
    };
    ("gpio.output_signal_max") => {
        256
    };
    ("gpio.output_signal_max", str) => {
        stringify!(256)
    };
    ("interrupts.status_registers") => {
        6
    };
    ("interrupts.status_registers", str) => {
        stringify!(6)
    };
    ("interrupts.disabled_interrupt") => {
        0
    };
    ("phy.combo_module") => {
        false
    };
    ("psram.octal_spi") => {
        false
    };
    ("psram.extmem_origin") => {
        1342177280
    };
    ("psram.extmem_origin", str) => {
        stringify!(1342177280)
    };
    ("rng.apb_cycle_wait_num") => {
        16
    };
    ("rng.apb_cycle_wait_num", str) => {
        stringify!(16)
    };
    ("rng.trng_supported") => {
        false
    };
    ("rng.is_lp_sys") => {
        false
    };
    ("sleep.light_sleep") => {
        false
    };
    ("sleep.deep_sleep") => {
        false
    };
    ("soc.cpu_has_branch_predictor") => {
        true
    };
    ("soc.cpu_has_csr_pc") => {
        false
    };
    ("soc.multi_core_enabled") => {
        true
    };
    ("soc.internal_memory_cached") => {
        true
    };
    ("wifi.has_wifi6") => {
        true
    };
    ("wifi.mac_version") => {
        3
    };
    ("wifi.mac_version", str) => {
        stringify!(3)
    };
    ("wifi.has_5g") => {
        false
    };
    ("wifi.csi_supported") => {
        true
    };
}
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_aes_key_length {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_aes_key_length { $(($pattern) => $code;)* ($other :
        tt) => {} } _for_each_inner_aes_key_length!((128));
        _for_each_inner_aes_key_length!((256)); _for_each_inner_aes_key_length!((128, 0,
        4)); _for_each_inner_aes_key_length!((256, 2, 6));
        _for_each_inner_aes_key_length!((bits(128), (256)));
        _for_each_inner_aes_key_length!((modes(128, 0, 4), (256, 2, 6)));
    };
}
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_dma_engine {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_dma_engine { $(($pattern) => $code;)* ($other : tt)
        => {} } _for_each_inner_dma_engine!(("AXI_GDMA"));
        _for_each_inner_dma_engine!((all("AXI_GDMA")));
    };
}
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_dma_channel {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_dma_channel { $(($pattern) => $code;)* ($other : tt)
        => {} } _for_each_inner_dma_channel!(("AXI_GDMA", DMA_AXI_CH0));
        _for_each_inner_dma_channel!(("AXI_GDMA", DMA_AXI_CH1));
        _for_each_inner_dma_channel!(("AXI_GDMA", DMA_AXI_CH2));
        _for_each_inner_dma_channel!(("AXI_GDMA", any_channel = AxiGdmaChannel));
        _for_each_inner_dma_channel!(("AXI_GDMA", DMA_AXI_CH0, 0, interrupt_in =
        AXI_PDMA_IN_CH0, interrupt_out = AXI_PDMA_OUT_CH0, compatible = [AES, SHA]));
        _for_each_inner_dma_channel!(("AXI_GDMA", DMA_AXI_CH1, 1, interrupt_in =
        AXI_PDMA_IN_CH1, interrupt_out = AXI_PDMA_OUT_CH1, compatible = [AES, SHA]));
        _for_each_inner_dma_channel!(("AXI_GDMA", DMA_AXI_CH2, 2, interrupt_in =
        AXI_PDMA_IN_CH2, interrupt_out = AXI_PDMA_OUT_CH2, compatible = [AES, SHA]));
        _for_each_inner_dma_channel!((names("AXI_GDMA", DMA_AXI_CH0), ("AXI_GDMA",
        DMA_AXI_CH1), ("AXI_GDMA", DMA_AXI_CH2)));
        _for_each_inner_dma_channel!((separate_any_type("AXI_GDMA", any_channel =
        AxiGdmaChannel))); _for_each_inner_dma_channel!((shared));
        _for_each_inner_dma_channel!((split("AXI_GDMA", DMA_AXI_CH0, 0, interrupt_in =
        AXI_PDMA_IN_CH0, interrupt_out = AXI_PDMA_OUT_CH0, compatible = [AES, SHA]),
        ("AXI_GDMA", DMA_AXI_CH1, 1, interrupt_in = AXI_PDMA_IN_CH1, interrupt_out =
        AXI_PDMA_OUT_CH1, compatible = [AES, SHA]), ("AXI_GDMA", DMA_AXI_CH2, 2,
        interrupt_in = AXI_PDMA_IN_CH2, interrupt_out = AXI_PDMA_OUT_CH2, compatible =
        [AES, SHA]))); _for_each_inner_dma_channel!((no_own_interrupt));
    };
}
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_dma_channel_peri_pair {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_dma_channel_peri_pair { $(($pattern) => $code;)*
        ($other : tt) => {} } _for_each_inner_dma_channel_peri_pair!(("AXI_GDMA",
        DMA_AXI_CH0, AES)); _for_each_inner_dma_channel_peri_pair!(("AXI_GDMA",
        DMA_AXI_CH0, SHA)); _for_each_inner_dma_channel_peri_pair!(("AXI_GDMA",
        DMA_AXI_CH1, AES)); _for_each_inner_dma_channel_peri_pair!(("AXI_GDMA",
        DMA_AXI_CH1, SHA)); _for_each_inner_dma_channel_peri_pair!(("AXI_GDMA",
        DMA_AXI_CH2, AES)); _for_each_inner_dma_channel_peri_pair!(("AXI_GDMA",
        DMA_AXI_CH2, SHA)); _for_each_inner_dma_channel_peri_pair!(("AXI_GDMA",
        any_channel = AxiGdmaChannel, AES));
        _for_each_inner_dma_channel_peri_pair!(("AXI_GDMA", any_channel = AxiGdmaChannel,
        SHA)); _for_each_inner_dma_channel_peri_pair!((channels("AXI_GDMA", DMA_AXI_CH0,
        AES), ("AXI_GDMA", DMA_AXI_CH0, SHA), ("AXI_GDMA", DMA_AXI_CH1, AES),
        ("AXI_GDMA", DMA_AXI_CH1, SHA), ("AXI_GDMA", DMA_AXI_CH2, AES), ("AXI_GDMA",
        DMA_AXI_CH2, SHA)));
        _for_each_inner_dma_channel_peri_pair!((any_channels("AXI_GDMA", any_channel =
        AxiGdmaChannel, AES), ("AXI_GDMA", any_channel = AxiGdmaChannel, SHA)));
    };
}
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_mem2mem_channel {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_mem2mem_channel { $(($pattern) => $code;)* ($other :
        tt) => {} } _for_each_inner_mem2mem_channel!(("AXI_GDMA", AxiGdma,
        AxiGdmaChannel, DMA_AXI_CH0, 6)); _for_each_inner_mem2mem_channel!(("AXI_GDMA",
        AxiGdma, AxiGdmaChannel, DMA_AXI_CH1, 7));
        _for_each_inner_mem2mem_channel!(("AXI_GDMA", AxiGdma, AxiGdmaChannel,
        DMA_AXI_CH2, 8)); _for_each_inner_mem2mem_channel!(("AXI_GDMA", AxiGdma,
        AxiGdmaChannel, 0, 6, 1, 7, 2, 8)); _for_each_inner_mem2mem_channel!(("AXI_GDMA",
        AxiGdma, AxiGdmaChannel)); _for_each_inner_mem2mem_channel!((channels("AXI_GDMA",
        AxiGdma, AxiGdmaChannel, DMA_AXI_CH0, 6), ("AXI_GDMA", AxiGdma, AxiGdmaChannel,
        DMA_AXI_CH1, 7), ("AXI_GDMA", AxiGdma, AxiGdmaChannel, DMA_AXI_CH2, 8)));
        _for_each_inner_mem2mem_channel!((erased("AXI_GDMA", AxiGdma, AxiGdmaChannel, 0,
        6, 1, 7, 2, 8))); _for_each_inner_mem2mem_channel!((engines("AXI_GDMA", AxiGdma,
        AxiGdmaChannel)));
    };
}
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! with_aes_dma_engine {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _with_inner_aes_dma_engine { $(($pattern) => $code;)* ($other : tt)
        => {} } _with_inner_aes_dma_engine!(("AXI_GDMA", AxiGdmaChannel));
    };
}
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! with_sha_dma_engine {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _with_inner_sha_dma_engine { $(($pattern) => $code;)* ($other : tt)
        => {} } _with_inner_sha_dma_engine!(("AXI_GDMA", AxiGdmaChannel));
    };
}
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_interrupt {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_interrupt { $(($pattern) => $code;)* ($other : tt)
        => {} } _for_each_inner_interrupt!(([disabled 0] 0));
        _for_each_inner_interrupt!(([reserved 0] 1));
        _for_each_inner_interrupt!(([reserved 1] 2));
        _for_each_inner_interrupt!(([reserved 2] 3));
        _for_each_inner_interrupt!(([reserved 3] 4));
        _for_each_inner_interrupt!(([reserved 4] 5));
        _for_each_inner_interrupt!(([reserved 5] 6));
        _for_each_inner_interrupt!(([reserved 6] 7));
        _for_each_inner_interrupt!(([reserved 7] 8));
        _for_each_inner_interrupt!(([reserved 8] 9));
        _for_each_inner_interrupt!(([reserved 9] 10));
        _for_each_inner_interrupt!(([reserved 10] 11));
        _for_each_inner_interrupt!(([reserved 11] 12));
        _for_each_inner_interrupt!(([reserved 12] 13));
        _for_each_inner_interrupt!(([reserved 13] 14));
        _for_each_inner_interrupt!(([reserved 14] 15));
        _for_each_inner_interrupt!(([vector 0] 16)); _for_each_inner_interrupt!(([vector
        1] 17)); _for_each_inner_interrupt!(([vector 2] 18));
        _for_each_inner_interrupt!(([vector 3] 19)); _for_each_inner_interrupt!(([vector
        4] 20)); _for_each_inner_interrupt!(([vector 5] 21));
        _for_each_inner_interrupt!(([vector 6] 22)); _for_each_inner_interrupt!(([vector
        7] 23)); _for_each_inner_interrupt!(([direct_bindable 0] 24));
        _for_each_inner_interrupt!(([direct_bindable 1] 25));
        _for_each_inner_interrupt!(([direct_bindable 2] 26));
        _for_each_inner_interrupt!(([direct_bindable 3] 27));
        _for_each_inner_interrupt!(([direct_bindable 4] 28));
        _for_each_inner_interrupt!(([direct_bindable 5] 29));
        _for_each_inner_interrupt!(([direct_bindable 6] 30));
        _for_each_inner_interrupt!(([direct_bindable 7] 31));
        _for_each_inner_interrupt!(([direct_bindable 8] 32));
        _for_each_inner_interrupt!(([direct_bindable 9] 33));
        _for_each_inner_interrupt!(([direct_bindable 10] 34));
        _for_each_inner_interrupt!(([direct_bindable 11] 35));
        _for_each_inner_interrupt!(([direct_bindable 12] 36));
        _for_each_inner_interrupt!(([direct_bindable 13] 37));
        _for_each_inner_interrupt!(([direct_bindable 14] 38));
        _for_each_inner_interrupt!(([direct_bindable 15] 39));
        _for_each_inner_interrupt!(([direct_bindable 16] 40));
        _for_each_inner_interrupt!(([direct_bindable 17] 41));
        _for_each_inner_interrupt!(([direct_bindable 18] 42));
        _for_each_inner_interrupt!(([direct_bindable 19] 43));
        _for_each_inner_interrupt!(([direct_bindable 20] 44));
        _for_each_inner_interrupt!(([direct_bindable 21] 45));
        _for_each_inner_interrupt!(([direct_bindable 22] 46));
        _for_each_inner_interrupt!(([direct_bindable 23] 47));
        _for_each_inner_interrupt!((all([disabled 0] 0), ([reserved 0] 1), ([reserved 1]
        2), ([reserved 2] 3), ([reserved 3] 4), ([reserved 4] 5), ([reserved 5] 6),
        ([reserved 6] 7), ([reserved 7] 8), ([reserved 8] 9), ([reserved 9] 10),
        ([reserved 10] 11), ([reserved 11] 12), ([reserved 12] 13), ([reserved 13] 14),
        ([reserved 14] 15), ([vector 0] 16), ([vector 1] 17), ([vector 2] 18), ([vector
        3] 19), ([vector 4] 20), ([vector 5] 21), ([vector 6] 22), ([vector 7] 23),
        ([direct_bindable 0] 24), ([direct_bindable 1] 25), ([direct_bindable 2] 26),
        ([direct_bindable 3] 27), ([direct_bindable 4] 28), ([direct_bindable 5] 29),
        ([direct_bindable 6] 30), ([direct_bindable 7] 31), ([direct_bindable 8] 32),
        ([direct_bindable 9] 33), ([direct_bindable 10] 34), ([direct_bindable 11] 35),
        ([direct_bindable 12] 36), ([direct_bindable 13] 37), ([direct_bindable 14] 38),
        ([direct_bindable 15] 39), ([direct_bindable 16] 40), ([direct_bindable 17] 41),
        ([direct_bindable 18] 42), ([direct_bindable 19] 43), ([direct_bindable 20] 44),
        ([direct_bindable 21] 45), ([direct_bindable 22] 46), ([direct_bindable 23]
        47)));
    };
}
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_classified_interrupt {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_classified_interrupt { $(($pattern) => $code;)*
        ($other : tt) => {} } _for_each_inner_classified_interrupt!(([direct_bindable 0]
        24)); _for_each_inner_classified_interrupt!(([direct_bindable 1] 25));
        _for_each_inner_classified_interrupt!(([direct_bindable 2] 26));
        _for_each_inner_classified_interrupt!(([direct_bindable 3] 27));
        _for_each_inner_classified_interrupt!(([direct_bindable 4] 28));
        _for_each_inner_classified_interrupt!(([direct_bindable 5] 29));
        _for_each_inner_classified_interrupt!(([direct_bindable 6] 30));
        _for_each_inner_classified_interrupt!(([direct_bindable 7] 31));
        _for_each_inner_classified_interrupt!(([direct_bindable 8] 32));
        _for_each_inner_classified_interrupt!(([direct_bindable 9] 33));
        _for_each_inner_classified_interrupt!(([direct_bindable 10] 34));
        _for_each_inner_classified_interrupt!(([direct_bindable 11] 35));
        _for_each_inner_classified_interrupt!(([direct_bindable 12] 36));
        _for_each_inner_classified_interrupt!(([direct_bindable 13] 37));
        _for_each_inner_classified_interrupt!(([direct_bindable 14] 38));
        _for_each_inner_classified_interrupt!(([direct_bindable 15] 39));
        _for_each_inner_classified_interrupt!(([direct_bindable 16] 40));
        _for_each_inner_classified_interrupt!(([direct_bindable 17] 41));
        _for_each_inner_classified_interrupt!(([direct_bindable 18] 42));
        _for_each_inner_classified_interrupt!(([direct_bindable 19] 43));
        _for_each_inner_classified_interrupt!(([direct_bindable 20] 44));
        _for_each_inner_classified_interrupt!(([direct_bindable 21] 45));
        _for_each_inner_classified_interrupt!(([direct_bindable 22] 46));
        _for_each_inner_classified_interrupt!(([direct_bindable 23] 47));
        _for_each_inner_classified_interrupt!(([vector 0] 16));
        _for_each_inner_classified_interrupt!(([vector 1] 17));
        _for_each_inner_classified_interrupt!(([vector 2] 18));
        _for_each_inner_classified_interrupt!(([vector 3] 19));
        _for_each_inner_classified_interrupt!(([vector 4] 20));
        _for_each_inner_classified_interrupt!(([vector 5] 21));
        _for_each_inner_classified_interrupt!(([vector 6] 22));
        _for_each_inner_classified_interrupt!(([vector 7] 23));
        _for_each_inner_classified_interrupt!(([reserved 0] 1));
        _for_each_inner_classified_interrupt!(([reserved 1] 2));
        _for_each_inner_classified_interrupt!(([reserved 2] 3));
        _for_each_inner_classified_interrupt!(([reserved 3] 4));
        _for_each_inner_classified_interrupt!(([reserved 4] 5));
        _for_each_inner_classified_interrupt!(([reserved 5] 6));
        _for_each_inner_classified_interrupt!(([reserved 6] 7));
        _for_each_inner_classified_interrupt!(([reserved 7] 8));
        _for_each_inner_classified_interrupt!(([reserved 8] 9));
        _for_each_inner_classified_interrupt!(([reserved 9] 10));
        _for_each_inner_classified_interrupt!(([reserved 10] 11));
        _for_each_inner_classified_interrupt!(([reserved 11] 12));
        _for_each_inner_classified_interrupt!(([reserved 12] 13));
        _for_each_inner_classified_interrupt!(([reserved 13] 14));
        _for_each_inner_classified_interrupt!(([reserved 14] 15));
        _for_each_inner_classified_interrupt!((direct_bindable([direct_bindable 0] 24),
        ([direct_bindable 1] 25), ([direct_bindable 2] 26), ([direct_bindable 3] 27),
        ([direct_bindable 4] 28), ([direct_bindable 5] 29), ([direct_bindable 6] 30),
        ([direct_bindable 7] 31), ([direct_bindable 8] 32), ([direct_bindable 9] 33),
        ([direct_bindable 10] 34), ([direct_bindable 11] 35), ([direct_bindable 12] 36),
        ([direct_bindable 13] 37), ([direct_bindable 14] 38), ([direct_bindable 15] 39),
        ([direct_bindable 16] 40), ([direct_bindable 17] 41), ([direct_bindable 18] 42),
        ([direct_bindable 19] 43), ([direct_bindable 20] 44), ([direct_bindable 21] 45),
        ([direct_bindable 22] 46), ([direct_bindable 23] 47)));
        _for_each_inner_classified_interrupt!((vector([vector 0] 16), ([vector 1] 17),
        ([vector 2] 18), ([vector 3] 19), ([vector 4] 20), ([vector 5] 21), ([vector 6]
        22), ([vector 7] 23))); _for_each_inner_classified_interrupt!((reserved([reserved
        0] 1), ([reserved 1] 2), ([reserved 2] 3), ([reserved 3] 4), ([reserved 4] 5),
        ([reserved 5] 6), ([reserved 6] 7), ([reserved 7] 8), ([reserved 8] 9),
        ([reserved 9] 10), ([reserved 10] 11), ([reserved 11] 12), ([reserved 12] 13),
        ([reserved 13] 14), ([reserved 14] 15)));
    };
}
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_interrupt_priority {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_interrupt_priority { $(($pattern) => $code;)*
        ($other : tt) => {} } _for_each_inner_interrupt_priority!((0, 1, Priority1,
        Level1)); _for_each_inner_interrupt_priority!((1, 2, Priority2, Level2));
        _for_each_inner_interrupt_priority!((2, 3, Priority3, Level3));
        _for_each_inner_interrupt_priority!((3, 4, Priority4, Level4));
        _for_each_inner_interrupt_priority!((4, 5, Priority5, Level5));
        _for_each_inner_interrupt_priority!((5, 6, Priority6, Level6));
        _for_each_inner_interrupt_priority!((6, 7, Priority7, Level7));
        _for_each_inner_interrupt_priority!((7, 8, Priority8, Level8));
        _for_each_inner_interrupt_priority!((all(0, 1, Priority1, Level1), (1, 2,
        Priority2, Level2), (2, 3, Priority3, Level3), (3, 4, Priority4, Level4), (4, 5,
        Priority5, Level5), (5, 6, Priority6, Level6), (6, 7, Priority7, Level7), (7, 8,
        Priority8, Level8)));
    };
}
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_sw_interrupt {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_sw_interrupt { $(($pattern) => $code;)* ($other :
        tt) => {} } _for_each_inner_sw_interrupt!((0, FROM_CPU_INTR0,
        software_interrupt0)); _for_each_inner_sw_interrupt!((1, FROM_CPU_INTR1,
        software_interrupt1)); _for_each_inner_sw_interrupt!((2, FROM_CPU_INTR2,
        software_interrupt2)); _for_each_inner_sw_interrupt!((3, FROM_CPU_INTR3,
        software_interrupt3)); _for_each_inner_sw_interrupt!((all(0, FROM_CPU_INTR0,
        software_interrupt0), (1, FROM_CPU_INTR1, software_interrupt1), (2,
        FROM_CPU_INTR2, software_interrupt2), (3, FROM_CPU_INTR3, software_interrupt3)));
    };
}
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_sha_algorithm {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_sha_algorithm { $(($pattern) => $code;)* ($other :
        tt) => {} } _for_each_inner_sha_algorithm!((Sha1, "SHA-1"(sizes : 64, 20, 8)
        (insecure_against : "collision", "length extension"), 0));
        _for_each_inner_sha_algorithm!((Sha224, "SHA-224"(sizes : 64, 28, 8)
        (insecure_against : "length extension"), 1));
        _for_each_inner_sha_algorithm!((Sha256, "SHA-256"(sizes : 64, 32, 8)
        (insecure_against : "length extension"), 2));
        _for_each_inner_sha_algorithm!((Sha384, "SHA-384"(sizes : 128, 48, 16)
        (insecure_against :), 3)); _for_each_inner_sha_algorithm!((Sha512,
        "SHA-512"(sizes : 128, 64, 16) (insecure_against : "length extension"), 4));
        _for_each_inner_sha_algorithm!((Sha512_224, "SHA-512/224"(sizes : 128, 28, 16)
        (insecure_against :), 5)); _for_each_inner_sha_algorithm!((Sha512_256,
        "SHA-512/256"(sizes : 128, 32, 16) (insecure_against :), 6));
        _for_each_inner_sha_algorithm!((algos(Sha1, "SHA-1"(sizes : 64, 20, 8)
        (insecure_against : "collision", "length extension"), 0), (Sha224,
        "SHA-224"(sizes : 64, 28, 8) (insecure_against : "length extension"), 1),
        (Sha256, "SHA-256"(sizes : 64, 32, 8) (insecure_against : "length extension"),
        2), (Sha384, "SHA-384"(sizes : 128, 48, 16) (insecure_against :), 3), (Sha512,
        "SHA-512"(sizes : 128, 64, 16) (insecure_against : "length extension"), 4),
        (Sha512_224, "SHA-512/224"(sizes : 128, 28, 16) (insecure_against :), 5),
        (Sha512_256, "SHA-512/256"(sizes : 128, 32, 16) (insecure_against :), 6)));
    };
}
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_wakeup_source {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_wakeup_source { $(($pattern) => $code;)* ($other :
        tt) => {} } _for_each_inner_wakeup_source!((Timer, 13));
        _for_each_inner_wakeup_source!((all(Timer, 13)));
    };
}
#[macro_export]
/// ESP-HAL must provide implementation for the following functions:
/// ```rust, no_run
/// // XTAL_CLK
///
/// fn configure_xtal_clk_impl(
///     _clocks: &mut ClockTree,
///     _old_config: Option<XtalClkConfig>,
///     _new_config: XtalClkConfig,
/// ) {
///     todo!()
/// }
///
/// // CPU_CLK
///
/// fn configure_cpu_clk_impl(
///     _clocks: &mut ClockTree,
///     _old_config: Option<CpuClkConfig>,
///     _new_config: CpuClkConfig,
/// ) {
///     todo!()
/// }
///
/// // APB_CLK
///
/// fn configure_apb_clk_impl(
///     _clocks: &mut ClockTree,
///     _old_config: Option<ApbClkConfig>,
///     _new_config: ApbClkConfig,
/// ) {
///     todo!()
/// }
/// ```
macro_rules! define_clock_tree_types {
    () => {
        /// Selects the output frequency of `XTAL_CLK`.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        #[cfg_attr(feature = "defmt", derive(defmt::Format))]
        pub enum XtalClkConfig {
            /// 40 MHz
            _40,
        }
        impl XtalClkConfig {
            pub fn value(&self) -> u32 {
                match self {
                    XtalClkConfig::_40 => 40000000,
                }
            }
        }
        /// Selects the output frequency of `CPU_CLK`.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        #[cfg_attr(feature = "defmt", derive(defmt::Format))]
        pub enum CpuClkConfig {
            /// 320 MHz
            _320,
        }
        impl CpuClkConfig {
            pub fn value(&self) -> u32 {
                match self {
                    CpuClkConfig::_320 => 320000000,
                }
            }
        }
        /// Selects the output frequency of `APB_CLK`.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        #[cfg_attr(feature = "defmt", derive(defmt::Format))]
        pub enum ApbClkConfig {
            /// 80 MHz
            _80,
        }
        impl ApbClkConfig {
            pub fn value(&self) -> u32 {
                match self {
                    ApbClkConfig::_80 => 80000000,
                }
            }
        }
        /// Represents the device's clock tree.
        pub struct ClockTree {
            xtal_clk: Option<XtalClkConfig>,
            cpu_clk: Option<CpuClkConfig>,
            apb_clk: Option<ApbClkConfig>,
        }
        impl ClockTree {
            /// Locks the clock tree for exclusive access.
            pub fn with<R>(f: impl FnOnce(&mut ClockTree) -> R) -> R {
                CLOCK_TREE.with(f)
            }
            /// Returns the current configuration of the XTAL_CLK clock tree node
            pub fn xtal_clk(&self) -> Option<XtalClkConfig> {
                self.xtal_clk
            }
            /// Returns the current configuration of the CPU_CLK clock tree node
            pub fn cpu_clk(&self) -> Option<CpuClkConfig> {
                self.cpu_clk
            }
            /// Returns the current configuration of the APB_CLK clock tree node
            pub fn apb_clk(&self) -> Option<ApbClkConfig> {
                self.apb_clk
            }
        }
        static CLOCK_TREE: ::esp_sync::NonReentrantMutex<ClockTree> =
            ::esp_sync::NonReentrantMutex::new(ClockTree {
                xtal_clk: None,
                cpu_clk: None,
                apb_clk: None,
            });
        static XTAL_CLK_FREQ_CACHE: ::core::sync::atomic::AtomicU32 =
            ::core::sync::atomic::AtomicU32::new(0);
        static CPU_CLK_FREQ_CACHE: ::core::sync::atomic::AtomicU32 =
            ::core::sync::atomic::AtomicU32::new(0);
        static APB_CLK_FREQ_CACHE: ::core::sync::atomic::AtomicU32 =
            ::core::sync::atomic::AtomicU32::new(0);
        pub fn configure_xtal_clk(clocks: &mut ClockTree, config: XtalClkConfig) {
            let old_config = clocks.xtal_clk.replace(config);
            refresh_xtal_clk_downstream(clocks);
            configure_xtal_clk_impl(clocks, old_config, config);
        }
        pub fn xtal_clk_config(clocks: &mut ClockTree) -> Option<XtalClkConfig> {
            clocks.xtal_clk
        }
        fn request_xtal_clk(_clocks: &mut ClockTree) {}
        fn release_xtal_clk(_clocks: &mut ClockTree) {}
        #[allow(unused_variables)]
        pub fn xtal_clk_config_frequency(clocks: &mut ClockTree, config: XtalClkConfig) -> u32 {
            config.value()
        }
        pub fn xtal_clk_frequency() -> u32 {
            XTAL_CLK_FREQ_CACHE.load(::core::sync::atomic::Ordering::Acquire)
        }
        pub fn configure_cpu_clk(clocks: &mut ClockTree, config: CpuClkConfig) {
            let old_config = clocks.cpu_clk.replace(config);
            refresh_cpu_clk_downstream(clocks);
            configure_cpu_clk_impl(clocks, old_config, config);
        }
        pub fn cpu_clk_config(clocks: &mut ClockTree) -> Option<CpuClkConfig> {
            clocks.cpu_clk
        }
        fn request_cpu_clk(_clocks: &mut ClockTree) {}
        fn release_cpu_clk(_clocks: &mut ClockTree) {}
        #[allow(unused_variables)]
        pub fn cpu_clk_config_frequency(clocks: &mut ClockTree, config: CpuClkConfig) -> u32 {
            config.value()
        }
        pub fn cpu_clk_frequency() -> u32 {
            CPU_CLK_FREQ_CACHE.load(::core::sync::atomic::Ordering::Acquire)
        }
        pub fn configure_apb_clk(clocks: &mut ClockTree, config: ApbClkConfig) {
            let old_config = clocks.apb_clk.replace(config);
            refresh_apb_clk_downstream(clocks);
            configure_apb_clk_impl(clocks, old_config, config);
        }
        pub fn apb_clk_config(clocks: &mut ClockTree) -> Option<ApbClkConfig> {
            clocks.apb_clk
        }
        fn request_apb_clk(_clocks: &mut ClockTree) {}
        fn release_apb_clk(_clocks: &mut ClockTree) {}
        #[allow(unused_variables)]
        pub fn apb_clk_config_frequency(clocks: &mut ClockTree, config: ApbClkConfig) -> u32 {
            config.value()
        }
        pub fn apb_clk_frequency() -> u32 {
            APB_CLK_FREQ_CACHE.load(::core::sync::atomic::Ordering::Acquire)
        }
        /// Clock tree configuration.
        ///
        /// The fields of this struct are optional, with the following caveats:
        /// - If `XTAL_CLK` is not specified, the crystal frequency will be automatically detected
        ///   if possible.
        /// - The CPU and its upstream clock nodes will be set to a default configuration.
        /// - Other unspecified clock sources will not be useable by peripherals.
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        #[cfg_attr(feature = "defmt", derive(defmt::Format))]
        #[instability::unstable]
        pub struct ClockConfig {
            /// `XTAL_CLK` configuration.
            pub xtal_clk: Option<XtalClkConfig>,
            /// `CPU_CLK` configuration.
            pub cpu_clk: Option<CpuClkConfig>,
            /// `APB_CLK` configuration.
            pub apb_clk: Option<ApbClkConfig>,
        }
        impl ClockConfig {
            fn apply(&self, clocks: &mut ClockTree) {
                if let Some(config) = self.xtal_clk {
                    configure_xtal_clk(clocks, config);
                }
                if let Some(config) = self.cpu_clk {
                    configure_cpu_clk(clocks, config);
                }
                if let Some(config) = self.apb_clk {
                    configure_apb_clk(clocks, config);
                }
            }
        }
        fn increment_reference_count(refcount: &mut u32) -> bool {
            let first = *refcount == 0;
            *refcount = unwrap!(refcount.checked_add(1), "Reference count overflow");
            first
        }
        fn decrement_reference_count(refcount: &mut u32) -> bool {
            *refcount = refcount.saturating_sub(1);
            let last = *refcount == 0;
            last
        }
        fn refresh_xtal_clk_downstream(clocks: &mut ClockTree) {
            if let Some(config) = clocks.xtal_clk {
                XTAL_CLK_FREQ_CACHE.store(
                    xtal_clk_config_frequency(clocks, config),
                    ::core::sync::atomic::Ordering::Release,
                );
            }
        }
        fn refresh_cpu_clk_downstream(clocks: &mut ClockTree) {
            if let Some(config) = clocks.cpu_clk {
                CPU_CLK_FREQ_CACHE.store(
                    cpu_clk_config_frequency(clocks, config),
                    ::core::sync::atomic::Ordering::Release,
                );
            }
        }
        fn refresh_apb_clk_downstream(clocks: &mut ClockTree) {
            if let Some(config) = clocks.apb_clk {
                APB_CLK_FREQ_CACHE.store(
                    apb_clk_config_frequency(clocks, config),
                    ::core::sync::atomic::Ordering::Release,
                );
            }
        }
    };
}
/// Implement the `Peripheral` enum and enable/disable/reset functions.
///
/// This macro is intended to be placed in `esp_hal::system`.
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! implement_peripheral_clocks {
    () => {
        #[doc(hidden)]
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        #[repr(u8)]
        #[cfg_attr(feature = "defmt", derive(defmt::Format))]
        pub enum Peripheral {
            /// AES peripheral clock signal
            Aes,
            /// AXI_GDMA peripheral clock signal
            AxiGdma,
            /// ECC peripheral clock signal
            Ecc,
            /// ECDSA peripheral clock signal
            Ecdsa,
            /// SHA peripheral clock signal
            Sha,
            /// SYSTIMER peripheral clock signal
            Systimer,
            /// USB_DEVICE peripheral clock signal
            UsbDevice,
        }
        impl Peripheral {
            const KEEP_ENABLED: &[Peripheral] = &[Self::Systimer, Self::UsbDevice];
            const COUNT: usize = Self::ALL.len();
            const ALL: &[Self] = &[
                Self::Aes,
                Self::AxiGdma,
                Self::Ecc,
                Self::Ecdsa,
                Self::Sha,
                Self::Systimer,
                Self::UsbDevice,
            ];
        }
        unsafe fn enable_internal_racey(peripheral: Peripheral, enable: bool) {
            match peripheral {
                Peripheral::Aes => {
                    crate::peripherals::HP_SYS_CLKRST::regs()
                        .crypto_ctrl0()
                        .modify(|_, w| {
                            w.reg_crypto_sys_clk_en()
                                .set_bit()
                                .reg_crypto_aes_clk_en()
                                .bit(enable)
                        });
                }
                Peripheral::AxiGdma => {
                    crate::peripherals::HP_SYS_CLKRST::regs()
                        .axi_pdma_ctrl0()
                        .modify(|_, w| w.reg_axi_pdma_sys_clk_en().bit(enable));
                }
                Peripheral::Ecc => {
                    crate::peripherals::HP_SYS_CLKRST::regs()
                        .crypto_ctrl0()
                        .modify(|_, w| {
                            w.reg_crypto_sys_clk_en()
                                .set_bit()
                                .reg_crypto_ecc_clk_en()
                                .bit(enable)
                        });
                }
                Peripheral::Ecdsa => {
                    crate::peripherals::HP_SYS_CLKRST::regs()
                        .crypto_ctrl0()
                        .modify(|_, w| {
                            w.reg_crypto_sys_clk_en()
                                .set_bit()
                                .reg_crypto_ecdsa_clk_en()
                                .bit(enable)
                        });
                }
                Peripheral::Sha => {
                    crate::peripherals::HP_SYS_CLKRST::regs()
                        .crypto_ctrl0()
                        .modify(|_, w| {
                            w.reg_crypto_sys_clk_en()
                                .set_bit()
                                .reg_crypto_sha_clk_en()
                                .bit(enable)
                        });
                }
                Peripheral::Systimer => {
                    crate::peripherals::HP_SYS_CLKRST::regs()
                        .systimer_ctrl0()
                        .modify(|_, w| {
                            w.reg_systimer_apb_clk_en()
                                .bit(enable)
                                .reg_systimer_clk_en()
                                .bit(enable)
                        });
                }
                Peripheral::UsbDevice => {
                    crate::peripherals::HP_SYS_CLKRST::regs()
                        .usb_device_ctrl0()
                        .modify(|_, w| w.reg_usb_device_apb_clk_en().bit(enable));
                }
            }
        }
        unsafe fn assert_peri_reset_racey(peripheral: Peripheral, reset: bool) {
            match peripheral {
                Peripheral::Aes => {
                    crate::peripherals::HP_SYS_CLKRST::regs()
                        .crypto_ctrl0()
                        .modify(|_, w| {
                            w.reg_crypto_aes_rst_en()
                                .bit(reset)
                                .reg_crypto_rst_en()
                                .clear_bit()
                                .reg_crypto_ds_rst_en()
                                .clear_bit()
                        });
                }
                Peripheral::AxiGdma => {
                    crate::peripherals::HP_SYS_CLKRST::regs()
                        .axi_pdma_ctrl0()
                        .modify(|_, w| w.reg_axi_pdma_rst_en().bit(reset));
                }
                Peripheral::Ecc => {
                    crate::peripherals::HP_SYS_CLKRST::regs()
                        .crypto_ctrl0()
                        .modify(|_, w| {
                            w.reg_crypto_ecc_rst_en()
                                .bit(reset)
                                .reg_crypto_ecdsa_rst_en()
                                .clear_bit()
                                .reg_crypto_rst_en()
                                .clear_bit()
                        });
                }
                Peripheral::Ecdsa => {
                    crate::peripherals::HP_SYS_CLKRST::regs()
                        .crypto_ctrl0()
                        .modify(|_, w| {
                            w.reg_crypto_ecdsa_rst_en()
                                .bit(reset)
                                .reg_crypto_rst_en()
                                .clear_bit()
                        });
                }
                Peripheral::Sha => {
                    crate::peripherals::HP_SYS_CLKRST::regs()
                        .crypto_ctrl0()
                        .modify(|_, w| w.reg_crypto_sha_rst_en().bit(reset));
                }
                Peripheral::Systimer => {
                    crate::peripherals::HP_SYS_CLKRST::regs()
                        .systimer_ctrl0()
                        .modify(|_, w| w.reg_systimer_rst_en().bit(reset));
                }
                Peripheral::UsbDevice => {
                    let _ = reset;
                }
            }
        }
    };
}
/// Macro to get the address range of the given memory region.
///
/// This macro provides two syntax options for each memory region:
///
/// - `memory_range!("region_name")` returns the address range as a range expression (`start..end`).
/// - `memory_range!(size as str, "region_name")` returns the size of the region as a string
///   literal.
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! memory_range {
    ("DRAM") => {
        0x2F010000..0x2F080000
    };
    (size as str, "DRAM") => {
        "458752"
    };
    ("DRAM2_UNINIT") => {
        0x2F000000..0x2F010000
    };
    (size as str, "DRAM2_UNINIT") => {
        "65536"
    };
}
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_peripheral {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_peripheral { $(($pattern) => $code;)* ($other : tt)
        => {} } _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO0 peripheral singleton"] GPIO0 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO1 peripheral singleton"]
        GPIO1 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO2 peripheral singleton"] GPIO2 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO3 peripheral singleton"]
        GPIO3 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO4 peripheral singleton"] GPIO4 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO5 peripheral singleton"]
        GPIO5 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO6 peripheral singleton"] GPIO6 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO7 peripheral singleton"]
        GPIO7 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO8 peripheral singleton"] GPIO8 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO9 peripheral singleton"]
        GPIO9 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO10 peripheral singleton"] GPIO10 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO11 peripheral singleton"]
        GPIO11 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO12 peripheral singleton"] GPIO12 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO13 peripheral singleton"]
        GPIO13 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO14 peripheral singleton"] GPIO14 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO15 peripheral singleton"]
        GPIO15 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO16 peripheral singleton"] GPIO16 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO17 peripheral singleton"]
        GPIO17 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO18 peripheral singleton"] GPIO18 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO19 peripheral singleton"]
        GPIO19 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO20 peripheral singleton"] GPIO20 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO21 peripheral singleton"]
        GPIO21 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO22 peripheral singleton"] GPIO22 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO23 peripheral singleton"]
        GPIO23 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO24 peripheral singleton"] GPIO24 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO25 peripheral singleton"]
        GPIO25 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO26 peripheral singleton"] GPIO26 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO27 peripheral singleton"]
        GPIO27 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO28 peripheral singleton"] GPIO28 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO30 peripheral singleton"]
        GPIO30 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO31 peripheral singleton"] GPIO31 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO32 peripheral singleton"]
        GPIO32 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO33 peripheral singleton"] GPIO33 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO34 peripheral singleton"]
        GPIO34 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO35 peripheral singleton"] GPIO35 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO36 peripheral singleton"]
        GPIO36 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO37 peripheral singleton"] GPIO37 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO38 peripheral singleton"]
        GPIO38 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO39 peripheral singleton"] GPIO39 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO40 peripheral singleton"]
        GPIO40 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO42 peripheral singleton"] GPIO42 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO43 peripheral singleton"]
        GPIO43 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO44 peripheral singleton"] GPIO44 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO45 peripheral singleton"]
        GPIO45 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO46 peripheral singleton"] GPIO46 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO47 peripheral singleton"]
        GPIO47 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO48 peripheral singleton"] GPIO48 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO49 peripheral singleton"]
        GPIO49 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO50 peripheral singleton"] GPIO50 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO51 peripheral singleton"]
        GPIO51 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO52 peripheral singleton"] GPIO52 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO53 peripheral singleton"]
        GPIO53 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO54 peripheral singleton"] GPIO54 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO55 peripheral singleton"]
        GPIO55 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO56 peripheral singleton"] GPIO56 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO57 peripheral singleton"]
        GPIO57 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO58 peripheral singleton"] GPIO58 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO59 peripheral singleton"]
        GPIO59 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "GPIO60 peripheral singleton"] GPIO60 <= virtual()));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO61 peripheral singleton"]
        GPIO61 <= virtual())); _for_each_inner_peripheral!((@ peri_type #[doc =
        "DMA_AXI_CH0 peripheral singleton"] DMA_AXI_CH0 <= virtual(AXI_PDMA_IN_CH0 : {
        bind_dma_in_interrupt, enable_dma_in_interrupt, disable_dma_in_interrupt },
        AXI_PDMA_OUT_CH0 : { bind_dma_out_interrupt, enable_dma_out_interrupt,
        disable_dma_out_interrupt }) (unstable))); _for_each_inner_peripheral!((@
        peri_type #[doc = "DMA_AXI_CH1 peripheral singleton"] DMA_AXI_CH1 <=
        virtual(AXI_PDMA_IN_CH1 : { bind_dma_in_interrupt, enable_dma_in_interrupt,
        disable_dma_in_interrupt }, AXI_PDMA_OUT_CH1 : { bind_dma_out_interrupt,
        enable_dma_out_interrupt, disable_dma_out_interrupt }) (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc =
        "DMA_AXI_CH2 peripheral singleton"] DMA_AXI_CH2 <= virtual(AXI_PDMA_IN_CH2 : {
        bind_dma_in_interrupt, enable_dma_in_interrupt, disable_dma_in_interrupt },
        AXI_PDMA_OUT_CH2 : { bind_dma_out_interrupt, enable_dma_out_interrupt,
        disable_dma_out_interrupt }) (unstable))); _for_each_inner_peripheral!((@
        peri_type #[doc = "EFUSE peripheral singleton"] EFUSE <= EFUSE() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "GPIO peripheral singleton"]
        GPIO <= GPIO() (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "HP_SYSTEM peripheral singleton"] HP_SYSTEM <= HP_SYS() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc =
        "HP_SYS_CLKRST peripheral singleton"] HP_SYS_CLKRST <= HP_SYS_CLKRST()
        (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "HP_APM peripheral singleton"] HP_APM <= HP_APM() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc =
        "HP_MEM_APM peripheral singleton"] HP_MEM_APM <= HP_MEM_APM() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "SYSTEM peripheral singleton"]
        SYSTEM <= HP_SYS() (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "CLIC peripheral singleton"] CLIC <= CLIC() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "CACHE peripheral singleton"]
        CACHE <= CACHE() (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "CPU_APM peripheral singleton"] CPU_APM <= CPU_APM() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "IO_MUX peripheral singleton"]
        IO_MUX <= IO_MUX() (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "IOMUX_MSPI_PIN peripheral singleton"] IOMUX_MSPI_PIN <= IOMUX_MSPI_PIN()
        (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "LP_AON peripheral singleton"] LP_AON <= LP_AON_CLKRST() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc =
        "LP_AON_CLKRST peripheral singleton"] LP_AON_CLKRST <= LP_AON_CLKRST()
        (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "LP_I2C_ANA_MST peripheral singleton"] LP_I2C_ANA_MST <= LP_I2C_ANA_MST()
        (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "PMU peripheral singleton"] PMU <= PMU() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc =
        "RTC_TIMER peripheral singleton"] RTC_TIMER <= LP_TIMER() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "LP_WDT peripheral singleton"]
        LP_WDT <= LP_WDT() (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "LPWR peripheral singleton"] LPWR <= LP_AON_CLKRST() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "RNG peripheral singleton"] RNG
        <= TRNG() (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "AXI_GDMA peripheral singleton"] AXI_GDMA <= AXI_DMA() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "AES peripheral singleton"] AES
        <= AES(AES : { bind_peri_interrupt, enable_peri_interrupt, disable_peri_interrupt
        }) (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "SHA peripheral singleton"] SHA <= SHA(SHA : { bind_peri_interrupt,
        enable_peri_interrupt, disable_peri_interrupt }) (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "ECC peripheral singleton"] ECC
        <= ECC() (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "ECDSA peripheral singleton"] ECDSA <= ECDSA(ECDSA : { bind_peri_interrupt,
        enable_peri_interrupt, disable_peri_interrupt }) (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "SYSTIMER peripheral singleton"]
        SYSTIMER <= SYSTIMER() (unstable))); _for_each_inner_peripheral!((@ peri_type
        #[doc = "TIMG0 peripheral singleton"] TIMG0 <= TIMG0() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "TIMG1 peripheral singleton"]
        TIMG1 <= TIMG1() (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "UART0 peripheral singleton"] UART0 <= UART0(UART0 : { bind_peri_interrupt,
        enable_peri_interrupt, disable_peri_interrupt }) (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "UART1 peripheral singleton"]
        UART1 <= UART1(UART1 : { bind_peri_interrupt, enable_peri_interrupt,
        disable_peri_interrupt }) (unstable))); _for_each_inner_peripheral!((@ peri_type
        #[doc = "UART2 peripheral singleton"] UART2 <= UART2(UART2 : {
        bind_peri_interrupt, enable_peri_interrupt, disable_peri_interrupt })
        (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "UART3 peripheral singleton"] UART3 <= UART3(UART3 : { bind_peri_interrupt,
        enable_peri_interrupt, disable_peri_interrupt }) (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "SPI0 peripheral singleton"]
        SPI0 <= SPI0() (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "PSRAM_MSPI peripheral singleton"] PSRAM_MSPI <= PSRAM_MSPI() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "PSRAM peripheral singleton"]
        PSRAM <= virtual() (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "SPI1 peripheral singleton"] SPI1 <= SPI1() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "SPI2 peripheral singleton"]
        SPI2 <= SPI2(SPI2 : { bind_peri_interrupt, enable_peri_interrupt,
        disable_peri_interrupt }) (unstable))); _for_each_inner_peripheral!((@ peri_type
        #[doc = "USB_DEVICE peripheral singleton"] USB_DEVICE <= USB_DEVICE(USB_DEVICE :
        { bind_peri_interrupt, enable_peri_interrupt, disable_peri_interrupt })
        (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "FLASH peripheral singleton"] FLASH <= virtual() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "ETH peripheral singleton"] ETH
        <= virtual() (unstable))); _for_each_inner_peripheral!((@ peri_type #[doc =
        "CPU_CTRL peripheral singleton"] CPU_CTRL <= virtual() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc =
        "SW_INTERRUPT peripheral singleton"] SW_INTERRUPT <= virtual() (unstable)));
        _for_each_inner_peripheral!((@ peri_type #[doc = "WIFI peripheral singleton"]
        WIFI <= virtual(WIFI_BB : { bind_bb_interrupt, enable_bb_interrupt,
        disable_bb_interrupt }, WIFI_MAC : { bind_mac_interrupt, enable_mac_interrupt,
        disable_mac_interrupt }, WIFI_PWR : { bind_pwr_interrupt, enable_pwr_interrupt,
        disable_pwr_interrupt }))); _for_each_inner_peripheral!((GPIO0));
        _for_each_inner_peripheral!((GPIO1)); _for_each_inner_peripheral!((GPIO2));
        _for_each_inner_peripheral!((GPIO3)); _for_each_inner_peripheral!((GPIO4));
        _for_each_inner_peripheral!((GPIO5)); _for_each_inner_peripheral!((GPIO6));
        _for_each_inner_peripheral!((GPIO7)); _for_each_inner_peripheral!((GPIO8));
        _for_each_inner_peripheral!((GPIO9)); _for_each_inner_peripheral!((GPIO10));
        _for_each_inner_peripheral!((GPIO11)); _for_each_inner_peripheral!((GPIO12));
        _for_each_inner_peripheral!((GPIO13)); _for_each_inner_peripheral!((GPIO14));
        _for_each_inner_peripheral!((GPIO15)); _for_each_inner_peripheral!((GPIO16));
        _for_each_inner_peripheral!((GPIO17)); _for_each_inner_peripheral!((GPIO18));
        _for_each_inner_peripheral!((GPIO19)); _for_each_inner_peripheral!((GPIO20));
        _for_each_inner_peripheral!((GPIO21)); _for_each_inner_peripheral!((GPIO22));
        _for_each_inner_peripheral!((GPIO23)); _for_each_inner_peripheral!((GPIO24));
        _for_each_inner_peripheral!((GPIO25)); _for_each_inner_peripheral!((GPIO26));
        _for_each_inner_peripheral!((GPIO27)); _for_each_inner_peripheral!((GPIO28));
        _for_each_inner_peripheral!((GPIO30)); _for_each_inner_peripheral!((GPIO31));
        _for_each_inner_peripheral!((GPIO32)); _for_each_inner_peripheral!((GPIO33));
        _for_each_inner_peripheral!((GPIO34)); _for_each_inner_peripheral!((GPIO35));
        _for_each_inner_peripheral!((GPIO36)); _for_each_inner_peripheral!((GPIO37));
        _for_each_inner_peripheral!((GPIO38)); _for_each_inner_peripheral!((GPIO39));
        _for_each_inner_peripheral!((GPIO40)); _for_each_inner_peripheral!((GPIO42));
        _for_each_inner_peripheral!((GPIO43)); _for_each_inner_peripheral!((GPIO44));
        _for_each_inner_peripheral!((GPIO45)); _for_each_inner_peripheral!((GPIO46));
        _for_each_inner_peripheral!((GPIO47)); _for_each_inner_peripheral!((GPIO48));
        _for_each_inner_peripheral!((GPIO49)); _for_each_inner_peripheral!((GPIO50));
        _for_each_inner_peripheral!((GPIO51)); _for_each_inner_peripheral!((GPIO52));
        _for_each_inner_peripheral!((GPIO53)); _for_each_inner_peripheral!((GPIO54));
        _for_each_inner_peripheral!((GPIO55)); _for_each_inner_peripheral!((GPIO56));
        _for_each_inner_peripheral!((GPIO57)); _for_each_inner_peripheral!((GPIO58));
        _for_each_inner_peripheral!((GPIO59)); _for_each_inner_peripheral!((GPIO60));
        _for_each_inner_peripheral!((GPIO61));
        _for_each_inner_peripheral!((DMA_AXI_CH0(unstable)));
        _for_each_inner_peripheral!((DMA_AXI_CH1(unstable)));
        _for_each_inner_peripheral!((DMA_AXI_CH2(unstable)));
        _for_each_inner_peripheral!((GPIO(unstable)));
        _for_each_inner_peripheral!((HP_SYSTEM(unstable)));
        _for_each_inner_peripheral!((HP_SYS_CLKRST(unstable)));
        _for_each_inner_peripheral!((HP_APM(unstable)));
        _for_each_inner_peripheral!((HP_MEM_APM(unstable)));
        _for_each_inner_peripheral!((SYSTEM(unstable)));
        _for_each_inner_peripheral!((CLIC(unstable)));
        _for_each_inner_peripheral!((CACHE(unstable)));
        _for_each_inner_peripheral!((CPU_APM(unstable)));
        _for_each_inner_peripheral!((IO_MUX(unstable)));
        _for_each_inner_peripheral!((IOMUX_MSPI_PIN(unstable)));
        _for_each_inner_peripheral!((LP_AON(unstable)));
        _for_each_inner_peripheral!((LP_AON_CLKRST(unstable)));
        _for_each_inner_peripheral!((LP_I2C_ANA_MST(unstable)));
        _for_each_inner_peripheral!((PMU(unstable)));
        _for_each_inner_peripheral!((RTC_TIMER(unstable)));
        _for_each_inner_peripheral!((LP_WDT(unstable)));
        _for_each_inner_peripheral!((LPWR(unstable)));
        _for_each_inner_peripheral!((RNG(unstable)));
        _for_each_inner_peripheral!((AXI_GDMA(unstable)));
        _for_each_inner_peripheral!((AES(unstable)));
        _for_each_inner_peripheral!((SHA(unstable)));
        _for_each_inner_peripheral!((ECDSA(unstable)));
        _for_each_inner_peripheral!((SYSTIMER(unstable)));
        _for_each_inner_peripheral!((TIMG0(unstable)));
        _for_each_inner_peripheral!((TIMG1(unstable)));
        _for_each_inner_peripheral!((UART0(unstable)));
        _for_each_inner_peripheral!((UART1(unstable)));
        _for_each_inner_peripheral!((UART2(unstable)));
        _for_each_inner_peripheral!((UART3(unstable)));
        _for_each_inner_peripheral!((SPI0(unstable)));
        _for_each_inner_peripheral!((PSRAM_MSPI(unstable)));
        _for_each_inner_peripheral!((PSRAM(unstable)));
        _for_each_inner_peripheral!((SPI1(unstable)));
        _for_each_inner_peripheral!((SPI2(unstable)));
        _for_each_inner_peripheral!((USB_DEVICE(unstable)));
        _for_each_inner_peripheral!((FLASH(unstable)));
        _for_each_inner_peripheral!((ETH(unstable)));
        _for_each_inner_peripheral!((CPU_CTRL(unstable)));
        _for_each_inner_peripheral!((SW_INTERRUPT(unstable)));
        _for_each_inner_peripheral!((WIFI)); _for_each_inner_peripheral!((AES, Aes, 4,
        AxiGdmaChannel)); _for_each_inner_peripheral!((SHA, Sha, 5, AxiGdmaChannel));
        _for_each_inner_peripheral!((all(@ peri_type #[doc =
        "GPIO0 peripheral singleton"] GPIO0 <= virtual()), (@ peri_type #[doc =
        "GPIO1 peripheral singleton"] GPIO1 <= virtual()), (@ peri_type #[doc =
        "GPIO2 peripheral singleton"] GPIO2 <= virtual()), (@ peri_type #[doc =
        "GPIO3 peripheral singleton"] GPIO3 <= virtual()), (@ peri_type #[doc =
        "GPIO4 peripheral singleton"] GPIO4 <= virtual()), (@ peri_type #[doc =
        "GPIO5 peripheral singleton"] GPIO5 <= virtual()), (@ peri_type #[doc =
        "GPIO6 peripheral singleton"] GPIO6 <= virtual()), (@ peri_type #[doc =
        "GPIO7 peripheral singleton"] GPIO7 <= virtual()), (@ peri_type #[doc =
        "GPIO8 peripheral singleton"] GPIO8 <= virtual()), (@ peri_type #[doc =
        "GPIO9 peripheral singleton"] GPIO9 <= virtual()), (@ peri_type #[doc =
        "GPIO10 peripheral singleton"] GPIO10 <= virtual()), (@ peri_type #[doc =
        "GPIO11 peripheral singleton"] GPIO11 <= virtual()), (@ peri_type #[doc =
        "GPIO12 peripheral singleton"] GPIO12 <= virtual()), (@ peri_type #[doc =
        "GPIO13 peripheral singleton"] GPIO13 <= virtual()), (@ peri_type #[doc =
        "GPIO14 peripheral singleton"] GPIO14 <= virtual()), (@ peri_type #[doc =
        "GPIO15 peripheral singleton"] GPIO15 <= virtual()), (@ peri_type #[doc =
        "GPIO16 peripheral singleton"] GPIO16 <= virtual()), (@ peri_type #[doc =
        "GPIO17 peripheral singleton"] GPIO17 <= virtual()), (@ peri_type #[doc =
        "GPIO18 peripheral singleton"] GPIO18 <= virtual()), (@ peri_type #[doc =
        "GPIO19 peripheral singleton"] GPIO19 <= virtual()), (@ peri_type #[doc =
        "GPIO20 peripheral singleton"] GPIO20 <= virtual()), (@ peri_type #[doc =
        "GPIO21 peripheral singleton"] GPIO21 <= virtual()), (@ peri_type #[doc =
        "GPIO22 peripheral singleton"] GPIO22 <= virtual()), (@ peri_type #[doc =
        "GPIO23 peripheral singleton"] GPIO23 <= virtual()), (@ peri_type #[doc =
        "GPIO24 peripheral singleton"] GPIO24 <= virtual()), (@ peri_type #[doc =
        "GPIO25 peripheral singleton"] GPIO25 <= virtual()), (@ peri_type #[doc =
        "GPIO26 peripheral singleton"] GPIO26 <= virtual()), (@ peri_type #[doc =
        "GPIO27 peripheral singleton"] GPIO27 <= virtual()), (@ peri_type #[doc =
        "GPIO28 peripheral singleton"] GPIO28 <= virtual()), (@ peri_type #[doc =
        "GPIO30 peripheral singleton"] GPIO30 <= virtual()), (@ peri_type #[doc =
        "GPIO31 peripheral singleton"] GPIO31 <= virtual()), (@ peri_type #[doc =
        "GPIO32 peripheral singleton"] GPIO32 <= virtual()), (@ peri_type #[doc =
        "GPIO33 peripheral singleton"] GPIO33 <= virtual()), (@ peri_type #[doc =
        "GPIO34 peripheral singleton"] GPIO34 <= virtual()), (@ peri_type #[doc =
        "GPIO35 peripheral singleton"] GPIO35 <= virtual()), (@ peri_type #[doc =
        "GPIO36 peripheral singleton"] GPIO36 <= virtual()), (@ peri_type #[doc =
        "GPIO37 peripheral singleton"] GPIO37 <= virtual()), (@ peri_type #[doc =
        "GPIO38 peripheral singleton"] GPIO38 <= virtual()), (@ peri_type #[doc =
        "GPIO39 peripheral singleton"] GPIO39 <= virtual()), (@ peri_type #[doc =
        "GPIO40 peripheral singleton"] GPIO40 <= virtual()), (@ peri_type #[doc =
        "GPIO42 peripheral singleton"] GPIO42 <= virtual()), (@ peri_type #[doc =
        "GPIO43 peripheral singleton"] GPIO43 <= virtual()), (@ peri_type #[doc =
        "GPIO44 peripheral singleton"] GPIO44 <= virtual()), (@ peri_type #[doc =
        "GPIO45 peripheral singleton"] GPIO45 <= virtual()), (@ peri_type #[doc =
        "GPIO46 peripheral singleton"] GPIO46 <= virtual()), (@ peri_type #[doc =
        "GPIO47 peripheral singleton"] GPIO47 <= virtual()), (@ peri_type #[doc =
        "GPIO48 peripheral singleton"] GPIO48 <= virtual()), (@ peri_type #[doc =
        "GPIO49 peripheral singleton"] GPIO49 <= virtual()), (@ peri_type #[doc =
        "GPIO50 peripheral singleton"] GPIO50 <= virtual()), (@ peri_type #[doc =
        "GPIO51 peripheral singleton"] GPIO51 <= virtual()), (@ peri_type #[doc =
        "GPIO52 peripheral singleton"] GPIO52 <= virtual()), (@ peri_type #[doc =
        "GPIO53 peripheral singleton"] GPIO53 <= virtual()), (@ peri_type #[doc =
        "GPIO54 peripheral singleton"] GPIO54 <= virtual()), (@ peri_type #[doc =
        "GPIO55 peripheral singleton"] GPIO55 <= virtual()), (@ peri_type #[doc =
        "GPIO56 peripheral singleton"] GPIO56 <= virtual()), (@ peri_type #[doc =
        "GPIO57 peripheral singleton"] GPIO57 <= virtual()), (@ peri_type #[doc =
        "GPIO58 peripheral singleton"] GPIO58 <= virtual()), (@ peri_type #[doc =
        "GPIO59 peripheral singleton"] GPIO59 <= virtual()), (@ peri_type #[doc =
        "GPIO60 peripheral singleton"] GPIO60 <= virtual()), (@ peri_type #[doc =
        "GPIO61 peripheral singleton"] GPIO61 <= virtual()), (@ peri_type #[doc =
        "DMA_AXI_CH0 peripheral singleton"] DMA_AXI_CH0 <= virtual(AXI_PDMA_IN_CH0 : {
        bind_dma_in_interrupt, enable_dma_in_interrupt, disable_dma_in_interrupt },
        AXI_PDMA_OUT_CH0 : { bind_dma_out_interrupt, enable_dma_out_interrupt,
        disable_dma_out_interrupt }) (unstable)), (@ peri_type #[doc =
        "DMA_AXI_CH1 peripheral singleton"] DMA_AXI_CH1 <= virtual(AXI_PDMA_IN_CH1 : {
        bind_dma_in_interrupt, enable_dma_in_interrupt, disable_dma_in_interrupt },
        AXI_PDMA_OUT_CH1 : { bind_dma_out_interrupt, enable_dma_out_interrupt,
        disable_dma_out_interrupt }) (unstable)), (@ peri_type #[doc =
        "DMA_AXI_CH2 peripheral singleton"] DMA_AXI_CH2 <= virtual(AXI_PDMA_IN_CH2 : {
        bind_dma_in_interrupt, enable_dma_in_interrupt, disable_dma_in_interrupt },
        AXI_PDMA_OUT_CH2 : { bind_dma_out_interrupt, enable_dma_out_interrupt,
        disable_dma_out_interrupt }) (unstable)), (@ peri_type #[doc =
        "EFUSE peripheral singleton"] EFUSE <= EFUSE() (unstable)), (@ peri_type #[doc =
        "GPIO peripheral singleton"] GPIO <= GPIO() (unstable)), (@ peri_type #[doc =
        "HP_SYSTEM peripheral singleton"] HP_SYSTEM <= HP_SYS() (unstable)), (@ peri_type
        #[doc = "HP_SYS_CLKRST peripheral singleton"] HP_SYS_CLKRST <= HP_SYS_CLKRST()
        (unstable)), (@ peri_type #[doc = "HP_APM peripheral singleton"] HP_APM <=
        HP_APM() (unstable)), (@ peri_type #[doc = "HP_MEM_APM peripheral singleton"]
        HP_MEM_APM <= HP_MEM_APM() (unstable)), (@ peri_type #[doc =
        "SYSTEM peripheral singleton"] SYSTEM <= HP_SYS() (unstable)), (@ peri_type #[doc
        = "CLIC peripheral singleton"] CLIC <= CLIC() (unstable)), (@ peri_type #[doc =
        "CACHE peripheral singleton"] CACHE <= CACHE() (unstable)), (@ peri_type #[doc =
        "CPU_APM peripheral singleton"] CPU_APM <= CPU_APM() (unstable)), (@ peri_type
        #[doc = "IO_MUX peripheral singleton"] IO_MUX <= IO_MUX() (unstable)), (@
        peri_type #[doc = "IOMUX_MSPI_PIN peripheral singleton"] IOMUX_MSPI_PIN <=
        IOMUX_MSPI_PIN() (unstable)), (@ peri_type #[doc = "LP_AON peripheral singleton"]
        LP_AON <= LP_AON_CLKRST() (unstable)), (@ peri_type #[doc =
        "LP_AON_CLKRST peripheral singleton"] LP_AON_CLKRST <= LP_AON_CLKRST()
        (unstable)), (@ peri_type #[doc = "LP_I2C_ANA_MST peripheral singleton"]
        LP_I2C_ANA_MST <= LP_I2C_ANA_MST() (unstable)), (@ peri_type #[doc =
        "PMU peripheral singleton"] PMU <= PMU() (unstable)), (@ peri_type #[doc =
        "RTC_TIMER peripheral singleton"] RTC_TIMER <= LP_TIMER() (unstable)), (@
        peri_type #[doc = "LP_WDT peripheral singleton"] LP_WDT <= LP_WDT() (unstable)),
        (@ peri_type #[doc = "LPWR peripheral singleton"] LPWR <= LP_AON_CLKRST()
        (unstable)), (@ peri_type #[doc = "RNG peripheral singleton"] RNG <= TRNG()
        (unstable)), (@ peri_type #[doc = "AXI_GDMA peripheral singleton"] AXI_GDMA <=
        AXI_DMA() (unstable)), (@ peri_type #[doc = "AES peripheral singleton"] AES <=
        AES(AES : { bind_peri_interrupt, enable_peri_interrupt, disable_peri_interrupt })
        (unstable)), (@ peri_type #[doc = "SHA peripheral singleton"] SHA <= SHA(SHA : {
        bind_peri_interrupt, enable_peri_interrupt, disable_peri_interrupt })
        (unstable)), (@ peri_type #[doc = "ECC peripheral singleton"] ECC <= ECC()
        (unstable)), (@ peri_type #[doc = "ECDSA peripheral singleton"] ECDSA <=
        ECDSA(ECDSA : { bind_peri_interrupt, enable_peri_interrupt,
        disable_peri_interrupt }) (unstable)), (@ peri_type #[doc =
        "SYSTIMER peripheral singleton"] SYSTIMER <= SYSTIMER() (unstable)), (@ peri_type
        #[doc = "TIMG0 peripheral singleton"] TIMG0 <= TIMG0() (unstable)), (@ peri_type
        #[doc = "TIMG1 peripheral singleton"] TIMG1 <= TIMG1() (unstable)), (@ peri_type
        #[doc = "UART0 peripheral singleton"] UART0 <= UART0(UART0 : {
        bind_peri_interrupt, enable_peri_interrupt, disable_peri_interrupt })
        (unstable)), (@ peri_type #[doc = "UART1 peripheral singleton"] UART1 <=
        UART1(UART1 : { bind_peri_interrupt, enable_peri_interrupt,
        disable_peri_interrupt }) (unstable)), (@ peri_type #[doc =
        "UART2 peripheral singleton"] UART2 <= UART2(UART2 : { bind_peri_interrupt,
        enable_peri_interrupt, disable_peri_interrupt }) (unstable)), (@ peri_type #[doc
        = "UART3 peripheral singleton"] UART3 <= UART3(UART3 : { bind_peri_interrupt,
        enable_peri_interrupt, disable_peri_interrupt }) (unstable)), (@ peri_type #[doc
        = "SPI0 peripheral singleton"] SPI0 <= SPI0() (unstable)), (@ peri_type #[doc =
        "PSRAM_MSPI peripheral singleton"] PSRAM_MSPI <= PSRAM_MSPI() (unstable)), (@
        peri_type #[doc = "PSRAM peripheral singleton"] PSRAM <= virtual() (unstable)),
        (@ peri_type #[doc = "SPI1 peripheral singleton"] SPI1 <= SPI1() (unstable)), (@
        peri_type #[doc = "SPI2 peripheral singleton"] SPI2 <= SPI2(SPI2 : {
        bind_peri_interrupt, enable_peri_interrupt, disable_peri_interrupt })
        (unstable)), (@ peri_type #[doc = "USB_DEVICE peripheral singleton"] USB_DEVICE
        <= USB_DEVICE(USB_DEVICE : { bind_peri_interrupt, enable_peri_interrupt,
        disable_peri_interrupt }) (unstable)), (@ peri_type #[doc =
        "FLASH peripheral singleton"] FLASH <= virtual() (unstable)), (@ peri_type #[doc
        = "ETH peripheral singleton"] ETH <= virtual() (unstable)), (@ peri_type #[doc =
        "CPU_CTRL peripheral singleton"] CPU_CTRL <= virtual() (unstable)), (@ peri_type
        #[doc = "SW_INTERRUPT peripheral singleton"] SW_INTERRUPT <= virtual()
        (unstable)), (@ peri_type #[doc = "WIFI peripheral singleton"] WIFI <=
        virtual(WIFI_BB : { bind_bb_interrupt, enable_bb_interrupt, disable_bb_interrupt
        }, WIFI_MAC : { bind_mac_interrupt, enable_mac_interrupt, disable_mac_interrupt
        }, WIFI_PWR : { bind_pwr_interrupt, enable_pwr_interrupt, disable_pwr_interrupt
        })))); _for_each_inner_peripheral!((singletons(GPIO0), (GPIO1), (GPIO2), (GPIO3),
        (GPIO4), (GPIO5), (GPIO6), (GPIO7), (GPIO8), (GPIO9), (GPIO10), (GPIO11),
        (GPIO12), (GPIO13), (GPIO14), (GPIO15), (GPIO16), (GPIO17), (GPIO18), (GPIO19),
        (GPIO20), (GPIO21), (GPIO22), (GPIO23), (GPIO24), (GPIO25), (GPIO26), (GPIO27),
        (GPIO28), (GPIO30), (GPIO31), (GPIO32), (GPIO33), (GPIO34), (GPIO35), (GPIO36),
        (GPIO37), (GPIO38), (GPIO39), (GPIO40), (GPIO42), (GPIO43), (GPIO44), (GPIO45),
        (GPIO46), (GPIO47), (GPIO48), (GPIO49), (GPIO50), (GPIO51), (GPIO52), (GPIO53),
        (GPIO54), (GPIO55), (GPIO56), (GPIO57), (GPIO58), (GPIO59), (GPIO60), (GPIO61),
        (DMA_AXI_CH0(unstable)), (DMA_AXI_CH1(unstable)), (DMA_AXI_CH2(unstable)),
        (GPIO(unstable)), (HP_SYSTEM(unstable)), (HP_SYS_CLKRST(unstable)),
        (HP_APM(unstable)), (HP_MEM_APM(unstable)), (SYSTEM(unstable)), (CLIC(unstable)),
        (CACHE(unstable)), (CPU_APM(unstable)), (IO_MUX(unstable)),
        (IOMUX_MSPI_PIN(unstable)), (LP_AON(unstable)), (LP_AON_CLKRST(unstable)),
        (LP_I2C_ANA_MST(unstable)), (PMU(unstable)), (RTC_TIMER(unstable)),
        (LP_WDT(unstable)), (LPWR(unstable)), (RNG(unstable)), (AXI_GDMA(unstable)),
        (AES(unstable)), (SHA(unstable)), (ECDSA(unstable)), (SYSTIMER(unstable)),
        (TIMG0(unstable)), (TIMG1(unstable)), (UART0(unstable)), (UART1(unstable)),
        (UART2(unstable)), (UART3(unstable)), (SPI0(unstable)), (PSRAM_MSPI(unstable)),
        (PSRAM(unstable)), (SPI1(unstable)), (SPI2(unstable)), (USB_DEVICE(unstable)),
        (FLASH(unstable)), (ETH(unstable)), (CPU_CTRL(unstable)),
        (SW_INTERRUPT(unstable)), (WIFI)));
        _for_each_inner_peripheral!((dma_eligible(AES, Aes, 4, AxiGdmaChannel), (SHA,
        Sha, 5, AxiGdmaChannel)));
    };
}
/// This macro can be used to generate code for each `GPIOn` instance.
///
/// For an explanation on the general syntax, as well as usage of individual/repeated
/// matchers, refer to [the crate-level documentation][crate#for_each-macros].
///
/// This macro has one option for its "Individual matcher" case:
///
/// Syntax: `($n:literal, $gpio:ident ($($digital_input_function:ident =>
/// $digital_input_signal:ident)*) ($($digital_output_function:ident =>
/// $digital_output_signal:ident)*) ($([$pin_attribute:ident])*))`
///
/// Macro fragments:
///
/// - `$n`: the number of the GPIO. For `GPIO0`, `$n` is 0.
/// - `$gpio`: the name of the GPIO.
/// - `$digital_input_function`: the number of the digital function, as an identifier (i.e. for
///   function 0 this is `_0`).
/// - `$digital_input_function`: the name of the digital function, as an identifier.
/// - `$digital_output_function`: the number of the digital function, as an identifier (i.e. for
///   function 0 this is `_0`).
/// - `$digital_output_function`: the name of the digital function, as an identifier.
/// - `$pin_attribute`: `Input` and/or `Output`, marks the possible directions of the GPIO.
///   Bracketed so that they can also be matched as optional fragments. Order is always Input first.
///
/// Example data: `(0, GPIO0 (_5 => EMAC_TX_CLK) (_1 => CLK_OUT1 _5 => EMAC_TX_CLK) ([Input]
/// [Output]))`
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_gpio {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_gpio { $(($pattern) => $code;)* ($other : tt) => {}
        } _for_each_inner_gpio!((0, GPIO0() () ([Input] [Output])));
        _for_each_inner_gpio!((1, GPIO1() () ([Input] [Output])));
        _for_each_inner_gpio!((2, GPIO2() () ([Input] [Output])));
        _for_each_inner_gpio!((3, GPIO3() () ([Input] [Output])));
        _for_each_inner_gpio!((4, GPIO4() () ([Input] [Output])));
        _for_each_inner_gpio!((5, GPIO5() () ([Input] [Output])));
        _for_each_inner_gpio!((6, GPIO6() () ([Input] [Output])));
        _for_each_inner_gpio!((7, GPIO7() () ([Input] [Output])));
        _for_each_inner_gpio!((8, GPIO8() () ([Input] [Output])));
        _for_each_inner_gpio!((9, GPIO9() () ([Input] [Output])));
        _for_each_inner_gpio!((10, GPIO10() () ([Input] [Output])));
        _for_each_inner_gpio!((11, GPIO11() () ([Input] [Output])));
        _for_each_inner_gpio!((12, GPIO12() () ([Input] [Output])));
        _for_each_inner_gpio!((13, GPIO13() () ([Input] [Output])));
        _for_each_inner_gpio!((14, GPIO14() () ([Input] [Output])));
        _for_each_inner_gpio!((15, GPIO15() () ([Input] [Output])));
        _for_each_inner_gpio!((16, GPIO16() () ([Input] [Output])));
        _for_each_inner_gpio!((17, GPIO17() () ([Input] [Output])));
        _for_each_inner_gpio!((18, GPIO18() () ([Input] [Output])));
        _for_each_inner_gpio!((19, GPIO19() () ([Input] [Output])));
        _for_each_inner_gpio!((20, GPIO20() () ([Input] [Output])));
        _for_each_inner_gpio!((21, GPIO21() () ([Input] [Output])));
        _for_each_inner_gpio!((22, GPIO22() () ([Input] [Output])));
        _for_each_inner_gpio!((23, GPIO23() () ([Input] [Output])));
        _for_each_inner_gpio!((24, GPIO24() () ([Input] [Output])));
        _for_each_inner_gpio!((25, GPIO25() () ([Input] [Output])));
        _for_each_inner_gpio!((26, GPIO26() () ([Input] [Output])));
        _for_each_inner_gpio!((27, GPIO27() () ([Input] [Output])));
        _for_each_inner_gpio!((28, GPIO28() () ([Input] [Output])));
        _for_each_inner_gpio!((30, GPIO30() () ([Input] [Output])));
        _for_each_inner_gpio!((31, GPIO31() () ([Input] [Output])));
        _for_each_inner_gpio!((32, GPIO32() () ([Input] [Output])));
        _for_each_inner_gpio!((33, GPIO33() () ([Input] [Output])));
        _for_each_inner_gpio!((34, GPIO34() () ([Input] [Output])));
        _for_each_inner_gpio!((35, GPIO35() () ([Input] [Output])));
        _for_each_inner_gpio!((36, GPIO36() () ([Input] [Output])));
        _for_each_inner_gpio!((37, GPIO37() () ([Input] [Output])));
        _for_each_inner_gpio!((38, GPIO38() () ([Input] [Output])));
        _for_each_inner_gpio!((39, GPIO39() () ([Input] [Output])));
        _for_each_inner_gpio!((40, GPIO40() () ([Input] [Output])));
        _for_each_inner_gpio!((42, GPIO42() () ([Input] [Output])));
        _for_each_inner_gpio!((43, GPIO43() () ([Input] [Output])));
        _for_each_inner_gpio!((44, GPIO44() () ([Input] [Output])));
        _for_each_inner_gpio!((45, GPIO45() () ([Input] [Output])));
        _for_each_inner_gpio!((46, GPIO46() () ([Input] [Output])));
        _for_each_inner_gpio!((47, GPIO47() () ([Input] [Output])));
        _for_each_inner_gpio!((48, GPIO48() () ([Input] [Output])));
        _for_each_inner_gpio!((49, GPIO49() () ([Input] [Output])));
        _for_each_inner_gpio!((50, GPIO50() () ([Input] [Output])));
        _for_each_inner_gpio!((51, GPIO51() () ([Input] [Output])));
        _for_each_inner_gpio!((52, GPIO52() () ([Input] [Output])));
        _for_each_inner_gpio!((53, GPIO53() () ([Input] [Output])));
        _for_each_inner_gpio!((54, GPIO54() () ([Input] [Output])));
        _for_each_inner_gpio!((55, GPIO55() () ([Input] [Output])));
        _for_each_inner_gpio!((56, GPIO56() () ([Input] [Output])));
        _for_each_inner_gpio!((57, GPIO57() () ([Input] [Output])));
        _for_each_inner_gpio!((58, GPIO58() () ([Input] [Output])));
        _for_each_inner_gpio!((59, GPIO59() () ([Input] [Output])));
        _for_each_inner_gpio!((60, GPIO60() () ([Input] [Output])));
        _for_each_inner_gpio!((61, GPIO61() () ([Input] [Output])));
        _for_each_inner_gpio!((all(0, GPIO0() () ([Input] [Output])), (1, GPIO1() ()
        ([Input] [Output])), (2, GPIO2() () ([Input] [Output])), (3, GPIO3() () ([Input]
        [Output])), (4, GPIO4() () ([Input] [Output])), (5, GPIO5() () ([Input]
        [Output])), (6, GPIO6() () ([Input] [Output])), (7, GPIO7() () ([Input]
        [Output])), (8, GPIO8() () ([Input] [Output])), (9, GPIO9() () ([Input]
        [Output])), (10, GPIO10() () ([Input] [Output])), (11, GPIO11() () ([Input]
        [Output])), (12, GPIO12() () ([Input] [Output])), (13, GPIO13() () ([Input]
        [Output])), (14, GPIO14() () ([Input] [Output])), (15, GPIO15() () ([Input]
        [Output])), (16, GPIO16() () ([Input] [Output])), (17, GPIO17() () ([Input]
        [Output])), (18, GPIO18() () ([Input] [Output])), (19, GPIO19() () ([Input]
        [Output])), (20, GPIO20() () ([Input] [Output])), (21, GPIO21() () ([Input]
        [Output])), (22, GPIO22() () ([Input] [Output])), (23, GPIO23() () ([Input]
        [Output])), (24, GPIO24() () ([Input] [Output])), (25, GPIO25() () ([Input]
        [Output])), (26, GPIO26() () ([Input] [Output])), (27, GPIO27() () ([Input]
        [Output])), (28, GPIO28() () ([Input] [Output])), (30, GPIO30() () ([Input]
        [Output])), (31, GPIO31() () ([Input] [Output])), (32, GPIO32() () ([Input]
        [Output])), (33, GPIO33() () ([Input] [Output])), (34, GPIO34() () ([Input]
        [Output])), (35, GPIO35() () ([Input] [Output])), (36, GPIO36() () ([Input]
        [Output])), (37, GPIO37() () ([Input] [Output])), (38, GPIO38() () ([Input]
        [Output])), (39, GPIO39() () ([Input] [Output])), (40, GPIO40() () ([Input]
        [Output])), (42, GPIO42() () ([Input] [Output])), (43, GPIO43() () ([Input]
        [Output])), (44, GPIO44() () ([Input] [Output])), (45, GPIO45() () ([Input]
        [Output])), (46, GPIO46() () ([Input] [Output])), (47, GPIO47() () ([Input]
        [Output])), (48, GPIO48() () ([Input] [Output])), (49, GPIO49() () ([Input]
        [Output])), (50, GPIO50() () ([Input] [Output])), (51, GPIO51() () ([Input]
        [Output])), (52, GPIO52() () ([Input] [Output])), (53, GPIO53() () ([Input]
        [Output])), (54, GPIO54() () ([Input] [Output])), (55, GPIO55() () ([Input]
        [Output])), (56, GPIO56() () ([Input] [Output])), (57, GPIO57() () ([Input]
        [Output])), (58, GPIO58() () ([Input] [Output])), (59, GPIO59() () ([Input]
        [Output])), (60, GPIO60() () ([Input] [Output])), (61, GPIO61() () ([Input]
        [Output]))));
    };
}
/// This macro can be used to generate code for each analog function of each GPIO.
///
/// For an explanation on the general syntax, as well as usage of individual/repeated
/// matchers, refer to [the crate-level documentation][crate#for_each-macros].
///
/// This macro has two options for its "Individual matcher" case:
///
/// - `all`: `($signal:ident, $gpio:ident)` - simple case where you only need identifiers
/// - `all_expanded`: `(($signal:ident, $group:ident $(, $number:literal)+), $gpio:ident)` -
///   expanded signal case, where you need the number(s) of a signal, or the general group to which
///   the signal belongs. For example, in case of `ADC2_CH3` the expanded form looks like
///   `(ADC2_CH3, ADCn_CHm, 2, 3)`.
///
/// Macro fragments:
///
/// - `$signal`: the name of the signal.
/// - `$group`: the name of the signal, with numbers replaced by placeholders. For `ADC2_CH3` this
///   is `ADCn_CHm`.
/// - `$number`: the numbers extracted from `$signal`.
/// - `$gpio`: the name of the GPIO.
///
/// Example data:
/// - `(ADC2_CH5, GPIO12)`
/// - `((ADC2_CH5, ADCn_CHm, 2, 5), GPIO12)`
///
/// The expanded syntax is only available when the signal has at least one numbered component.
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_analog_function {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_analog_function { $(($pattern) => $code;)* ($other :
        tt) => {} } _for_each_inner_analog_function!((all));
        _for_each_inner_analog_function!((all_expanded));
    };
}
/// This macro can be used to generate code for each LP/RTC function of each GPIO.
///
/// For an explanation on the general syntax, as well as usage of individual/repeated
/// matchers, refer to [the crate-level documentation][crate#for_each-macros].
///
/// This macro has two options for its "Individual matcher" case:
///
/// - `all`: `($signal:ident, $gpio:ident)` - simple case where you only need identifiers
/// - `all_expanded`: `(($signal:ident, $group:ident $(, $number:literal)+), $gpio:ident)` -
///   expanded signal case, where you need the number(s) of a signal, or the general group to which
///   the signal belongs. For example, in case of `SAR_I2C_SCL_1` the expanded form looks like
///   `(SAR_I2C_SCL_1, SAR_I2C_SCL_n, 1)`.
///
/// Macro fragments:
///
/// - `$signal`: the name of the signal.
/// - `$group`: the name of the signal, with numbers replaced by placeholders. For `ADC2_CH3` this
///   is `ADCn_CHm`.
/// - `$number`: the numbers extracted from `$signal`.
/// - `$gpio`: the name of the GPIO.
///
/// Example data:
/// - `(RTC_GPIO15, GPIO12)`
/// - `((RTC_GPIO15, RTC_GPIOn, 15), GPIO12)`
///
/// The expanded syntax is only available when the signal has at least one numbered component.
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_lp_function {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_lp_function { $(($pattern) => $code;)* ($other : tt)
        => {} } _for_each_inner_lp_function!((all));
        _for_each_inner_lp_function!((all_expanded));
    };
}
/// This macro can be used to generate code for each IOMUX digital function of each GPIO.
///
/// IOMUX functions are the alternate digital functions configured via the IO_MUX registers.
/// Use this to implement signal-specific traits for peripherals whose pins must bypass the
/// GPIO matrix (e.g., EMAC, USB).
///
/// For an explanation on the general syntax, as well as usage of individual/repeated
/// matchers, refer to [the crate-level documentation][crate#for_each-macros].
///
/// This macro has two options for its "Individual matcher" case:
///
/// - `all`: `($signal:ident, $gpio:ident, $af:ident)` - simple case where you only need
///   identifiers, and maybe the alternate function.
/// - `all_expanded`: `(($signal:ident, $group:ident $(, $number:literal)+), $gpio:ident,
///   $af:ident)` - expanded signal case, where you need the number(s) of a signal, or the general
///   group to which the signal belongs.
///
/// Macro fragments:
///
/// - `$signal`: the name of the signal.
/// - `$group`: the name of the signal, with numbers replaced by placeholders.
/// - `$number`: the numbers extracted from `$signal`.
/// - `$gpio`: the name of the GPIO.
/// - `$af`: the alternate function number, as an identifier (e.g. `_5`).
///
/// Example data:
/// - `(EMAC_RXD0, GPIO25, _5)`
/// - `((EMAC_RXDn, EMAC_RXDn, 0), GPIO25, _5)`
///
/// The expanded syntax is only available when the signal has at least one numbered component.
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! for_each_iomux_function {
    ($($pattern:tt => $code:tt;)*) => {
        macro_rules! _for_each_inner_iomux_function { $(($pattern) => $code;)* ($other :
        tt) => {} } _for_each_inner_iomux_function!((all));
        _for_each_inner_iomux_function!((all_expanded));
    };
}
/// Defines the `InputSignal` and `OutputSignal` enums.
///
/// This macro is intended to be called in esp-hal only.
#[macro_export]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! define_io_mux_signals {
    () => {
        #[allow(non_camel_case_types, clippy::upper_case_acronyms)]
        #[derive(Debug, PartialEq, Copy, Clone)]
        #[cfg_attr(feature = "defmt", derive(defmt::Format))]
        #[doc(hidden)]
        pub enum InputSignal {
            U0RXD    = 10,
            EMAC_MDI = 107,
        }
        #[allow(non_camel_case_types, clippy::upper_case_acronyms)]
        #[derive(Debug, PartialEq, Copy, Clone)]
        #[cfg_attr(feature = "defmt", derive(defmt::Format))]
        #[doc(hidden)]
        pub enum OutputSignal {
            U0TXD    = 10,
            EMAC_MDC = 108,
            EMAC_MDO = 109,
            GPIO     = 256,
        }
    };
}
/// Defines and implements the `io_mux_reg` function.
///
/// The generated function has the following signature:
///
/// ```rust,ignore
/// pub(crate) fn io_mux_reg(gpio_num: u8) -> &'static crate::pac::io_mux::GPIO0 {
///     // ...
/// # unimplemented!()
/// }
/// ```
///
/// This macro is intended to be called in esp-hal only.
#[macro_export]
#[expect(clippy::crate_in_macro_def)]
#[cfg_attr(docsrs, doc(cfg(feature = "_device-selected")))]
macro_rules! define_io_mux_reg {
    () => {
        pub(crate) fn io_mux_reg(gpio_num: u8) -> &'static crate::pac::io_mux::GPIO {
            crate::peripherals::IO_MUX::regs().gpio(gpio_num as usize)
        }
    };
}
